export default [
    { id: 0, color: 'orange', letter: 'A' },
    { id: 1, color: 'blue', letter: 'B' },
    { id: 2, color: 'orange', letter: 'C' },
    { id: 3, color: 'orange', letter: 'D' },
    { id: 4, color: 'green', letter: 'E' },
    { id: 5, color: 'yellow', letter: 'F' },
    { id: 6, color: 'blue', letter: 'G' },
    { id: 7, color: 'orange', letter: 'H' },
    { id: 8, color: 'red', letter: 'I' },
    { id: 9, color: 'green', letter: 'J' },
    { id: 10, color: 'orange', letter: 'K' },
    { id: 11, color: 'yellow', letter: 'L' },
    { id: 12, color: 'blue', letter: 'M' },
    { id: 13, color: 'red', letter: 'N' },
    { id: 14, color: 'red', letter: 'O' },
    { id: 15, color: 'blue', letter: 'P' },
    { id: 16, color: 'red', letter: 'Q' },
    { id: 17, color: 'blue', letter: 'R' },
    { id: 18, color: 'yellow', letter: 'S' },
    { id: 19, color: 'blue', letter: 'T' },
    { id: 20, color: 'green', letter: 'U' },
    { id: 21, color: 'red', letter: 'V' },
    { id: 22, color: 'red', letter: 'W' },
    { id: 23, color: 'orange', letter: 'X' },
    { id: 24, color: 'green', letter: 'Y' },
    { id: 25, color: 'blue', letter: 'Z' }
]