export default [ { id: 1, color: 'red' },
{ id: 2, color: 'yellow' },
{ id: 3, color: 'yellow' },
{ id: 4, color: 'blue' },
{ id: 5, color: 'orange' },
{ id: 6, color: 'red' },
{ id: 7, color: 'green' },
{ id: 8, color: 'yellow' },
{ id: 9, color: 'blue' },
{ id: 10, color: 'red' },
{ id: 11, color: 'red' },
{ id: 12, color: 'blue' },
{ id: 13, color: 'red' },
{ id: 14, color: 'yellow' },
{ id: 15, color: 'red' },
{ id: 16, color: 'green' },
{ id: 17, color: 'yellow' },
{ id: 18, color: 'orange' },
{ id: 19, color: 'blue' },
{ id: 20, color: 'green' },
{ id: 21, color: 'orange' },
{ id: 22, color: 'yellow' },
{ id: 23, color: 'yellow' },
{ id: 24, color: 'orange' },

]